add unicode ranges for Emoji 9 and 10
mathiasbynens/regenerate-unicode-properties pull request #1
Opened 2017-03-06 11:10 UTC by patrickkettner

pulled from the latest [emoji-data.txt](http://unicode.org/Public/emoji/5.0/emoji-data.txt), in order to fix [emoji-regex#10](https://github.com/mathiasbynens/emoji-regex/issues/10)

2017-03-06 12:24 UTC, mathiasbynens commented
Could you look into the failing test please? Thanks!

On Mar 6, 2017 08:10, "patrick kettner" <notifications@github.com> wrote:

> pulled from the latest emoji-data.txt
> <http://unicode.org/Public/emoji/5.0/emoji-data.txt>, in order to fix
> emoji-regex#10 <https://github.com/mathiasbynens/emoji-regex/issues/10>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mathiasbynens/regenerate-unicode-properties/pull/1
> Commit Summary
>
>    - add unicode ranges for Emoji 9 and 10
>
> File Changes
>
>    - *M* Binary_Property/Emoji.js
>    <https://github.com/mathiasbynens/regenerate-unicode-properties/pull/1/files#diff-0>
>    (2)
>
> Patch Links:
>
>    - https://github.com/mathiasbynens/regenerate-
>    unicode-properties/pull/1.patch
>    <https://github.com/mathiasbynens/regenerate-unicode-properties/pull/1.patch>
>    - https://github.com/mathiasbynens/regenerate-
>    unicode-properties/pull/1.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mathiasbynens/regenerate-unicode-properties/pull/1>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAFAFusN_VCPK-fmpdWZ61RAttUPDYrXks5ri-mlgaJpZM4MUA0g>
> .
>

2017-03-06 17:21 UTC, mathiasbynens commented
Did you edit this file manually? The idea of this repo is that [`npm run build`](https://github.com/mathiasbynens/regenerate-unicode-properties/blob/c33b350d82dd47bdfa43cf3a50f58341f0d5d664/package.json#L44) generates all the output, including `Binary_Property/Emoji.js`. So, to do what you want, [unicode-tr51](https://github.com/mathiasbynens/unicode-tr51) must be updated to use the latest data, after which this project can update its dependencies and run the build again.

2017-03-06 18:50 UTC, mxstbr commented
It's dependencies all the way down...

2017-03-06 19:09 UTC, patrickkettner commented
created PR for the correct change, and updated this to just be a test addition for level 9 emoji

2017-03-07 20:00 UTC, mathiasbynens requested changes
Could you update the unicode-tr51 dependency to the latest version? Then this looks good to go 👍

2017-03-07 20:00 UTC, mathiasbynens commented on tests/tests.js
> +		require('../Binary_Property/Emoji.js').toRegExp().test('🤡')
Let’s use `'\u{1F921}'` instead so the test files remain ASCII-safe.

2017-03-07 20:01 UTC, mathiasbynens commented on tests/tests.js
> +		require('../Binary_Property/Emoji.js').toRegExp().test('🤡')
```js
require('../Binary_Property/Emoji.js').toRegExp().test('\u{1F921}') // U+1F921 CLOWN FACE
```

2017-03-07 20:15 UTC, patrickkettner commented
done

2017-03-07 20:16 UTC, mathiasbynens approved these changes

2017-03-08 16:38 UTC, mathiasbynens commented
[Huh?](https://travis-ci.org/mathiasbynens/regenerate-unicode-properties/jobs/208726335#L899)

```
Creating Binary_Property/Emoji_Component.js…
module.js:472
    throw err;
    ^
Error: Cannot find module 'unicode-tr51/Emoji_Component.js'
```

2017-03-08 17:29 UTC, mathiasbynens commented on package.json
> +    "unicode-tr51": "^8.0.0"
Could you update this to v8.0.1 explicitly please? 8.0.0 is missing `Emoji_Component.js`.

2017-03-08 18:22 UTC, patrickkettner commented on package.json
> +    "unicode-tr51": "^8.0.0"
done

2017-03-08 18:48 UTC, merged